Updating documentation for ECR
shadow-robot/sr_documentation pull request #7
Opened 2022-02-07 16:19 UTC by biofotis

## Proposed changes

Updating documentation for ECR

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2022-02-08 16:07 UTC, BenStarmerSmith approved these changes

2022-02-09 11:01 UTC, maxzieba requested changes

2022-02-09 11:01 UTC, maxzieba commented on docs/user_guide/1_runnining_dockers.rst
> +To authentication for Public ECR repos such as dexterous hand images just run this command (it last 12 hours): ```aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --
To authenticate

2022-02-09 11:11 UTC, maxzieba approved these changes

2022-02-09 11:12 UTC, merged